name: Build and Push to GHCR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker tag to use (e.g., v1.0.4)'
        required: true
        default: 'v1.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: GHCR_BUILD

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT_TOKEN }}
        run: |
          echo "$GHCR_PAT" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set image name
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER}/beneficiary-backend"
          IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Build and Push Docker image
        run: |
          echo "Building and tagging image as $IMAGE_NAME:$TAG"
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
          echo "Pushing image: $IMAGE_NAME:$TAG"
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
          echo "$IMAGE_NAME:$TAG" > image.txt

      - name: Upload image URI
        uses: actions/upload-artifact@v4
        with:
          name: image-uri
          path: image.txt
