name: Deploy to DEV
on:
  push:
    branches:
      - main
jobs:
   Deploy_on_UBA:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - 
      name: Deploy Stack
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_NAME_TEKDI }}
          username: ${{ secrets.USERNAME_TEKDI }}
          key: ${{ secrets.EC2_SSH_KEY_TEKDI }}
          port: ${{ secrets.PORT_TEKDI }}
          script: |    
               cd ${{ secrets.TARGET_DIR_TEKDI }}
               if [ -f .env ]; then
               rm .env
               fi
               echo '${{ secrets.DEV_ENV }}' > .env
               ls -ltra
               ./deploy.sh
#Testing
